### ISSUE TITLE
Math does not seem to render in the tutorial

### ISSUE THREAD

**Issue by moorepants** [CameronDevine/StateModelRnD#8]
![selection_417](https://user-images.githubusercontent.com/276007/51955965-b101eb80-23fa-11e9-9cf2-0cba2b2bd2b9.png)

**Comment by CameronDevine** [comment]
What OS browser combination are you using when you see this?

**Comment by moorepants** [comment]
Ubuntu 18.10 and latest firefox.

**Comment by CameronDevine** [comment]
I installed Firefox 64.0 on Ubuntu Mate 18.04, but I wasn't able to recreate the issue.

**Comment by ricopicone** [comment]
I reproduced this once or twice in Chrome Version 71.0.3578.98 (Official Build) (64-bit) on MacOS Version 10.14.2 (18C54), but upon page refresh the math rendered fine. Possibly occasional requests to the external math rendering server (previously a MathJax server, but I don't recall the current one) are failing? @moorepants what happens when you refresh?

**Comment by CameronDevine** [comment]
@moorepants I just pushed a change which may fix this issue. Could you test this again?

**Comment by moorepants** [comment]
Renders in Firefox and Chrome for me. Thanks.
